spring:
  application:
    name: rouin

server.port: 10180

logging:
  level:
    root: ERROR
    al.rouin: WARN


rouin:
  plaid:
    environment: DEVELOPMENT # SANDBOX, DEVELOPMENT, PRODUCTION
    client-id: ${PLAID_CLIENT_ID}
    secret: ${PLAID_SECRET}
    version: 2020-09-14
    country-code: CA
    language: en