spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


logging:
  level:
    root: INFO
    al.rouin: DEBUG


rouin:
  user:
    email: test@test.com
    user-id: 6446271d-e744-4d71-a2f6-92e2242ef9f8
    access-token: ${TEST_ACCESS_TOKEN}
    item-id: ${TEST_ITEM_ID}
  external:
    plaid:
      environment: SANDBOX # SANDBOX, DEVELOPMENT, PRODUCTION