DROP TABLE IF EXISTS users;


CREATE TABLE users(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(256) NOT NULL UNIQUE,
    email VARCHAR(256) NOT NULL UNIQUE,
    created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE access_tokens(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(256) NOT NULL,
    access_token VARCHAR(256) NOT NULL UNIQUE,
    item_id VARCHAR(256) NOT NULL UNIQUE,
    created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE accounts(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    account_id VARCHAR(256) NOT NULL UNIQUE,
    reference_id VARCHAR(256) NOT NULL UNIQUE,
    user_id VARCHAR(256) NOT NULL,
    name VARCHAR(256) NOT NULL,
    alias_name VARCHAR(256) NOT NULL,
    official_name VARCHAR(256) NULL,
    account_type VARCHAR(256) NOT NULL,
    account_sub_type VARCHAR(256) NULL,
    deleted TINYINT(1) NOT NULL DEFAULT FALSE,
    created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE transactions(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    transaction_id VARCHAR(256) NOT NULL UNIQUE,
    reference_id VARCHAR(256) NOT NULL UNIQUE,
    user_id VARCHAR(256) NOT NULL,
    account_id VARCHAR(256) NOT NULL,
    category_id VARCHAR(256) NOT NULL,
    name VARCHAR(256) NOT NULL,
    date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    amount DOUBLE NOT NULL DEFAULT 0,
    currency VARCHAR(3) NOT NULL,
    description VARCHAR(256) NOT NULL,
    deleted TINYINT(1) NOT NULL DEFAULT FALSE,
    created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE categories(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category_id VARCHAR(256) NOT NULL UNIQUE,
    user_id VARCHAR(256) NOT NULL,
    name VARCHAR(256) NOT NULL,
    created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE budgets(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    budget_id VARCHAR(256) NOT NULL UNIQUE,
    category_id VARCHAR(256) NOT NULL,
    user_id VARCHAR(256) NOT NULL,
    amount DOUBLE NOT NULL,
    budget_year INT NOT NULL,
    budget_month INT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE exchange_rates(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    exchange_rate_id VARCHAR(256) NOT NULL UNIQUE,
    from_currency VARCHAR(3) NOT NULL,
    to_currency VARCHAR(3) NOT NULL,
    exchange_rate DOUBLE NOT NULL,
    created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO exchange_rates(id, exchange_rate_id, from_currency, to_currency, exchange_rate)
VALUES (1, 'CAD_KRW', 'CAD', 'KRW', 940.135004);
INSERT INTO exchange_rates(id, exchange_rate_id, from_currency, to_currency, exchange_rate)
VALUES (2, 'KRW_CAD', 'KRW', 'CAD', 0.001064);