DROP TABLE IF EXISTS users;


CREATE TABLE users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(256) NOT NULL UNIQUE,
  email VARCHAR(256) NOT NULL UNIQUE
);


CREATE TABLE access_tokens (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(256) NOT NULL,
  access_token VARCHAR(256) NOT NULL UNIQUE,
  item_id VARCHAR(256) NOT NULL UNIQUE
);