DROP TABLE IF EXISTS users;


CREATE TABLE users(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(256) NOT NULL UNIQUE,
  email VARCHAR(256) NOT NULL UNIQUE
);


CREATE TABLE access_tokens(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(256) NOT NULL,
  access_token VARCHAR(256) NOT NULL UNIQUE,
  item_id VARCHAR(256) NOT NULL UNIQUE
);


CREATE TABLE accounts(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_id VARCHAR(256) NOT NULL UNIQUE,
  plaid_account_id VARCHAR(256) NOT NULL UNIQUE,
  user_id VARCHAR(256) NOT NULL,
  name VARCHAR(256) NOT NULL,
  alias_name VARCHAR(256) NOT NULL,
  official_name VARCHAR(256) NULL,
  account_type VARCHAR(256) NOT NULL,
  account_sub_type VARCHAR(256) NULL
);